---
- block:
  - name: "Add GPG keys from keyserver"
    apt_key: keyserver={{item.keyserver}} id={{item.id}}
    with_items:
      - {keyserver: p80.pool.sks-keyservers.net, id: 58118E89F3A912897C070ADBF76221572C52609D}
      - {keyserver: keyserver.ubuntu.com, id: D1742AD60D811D58}

  - name: "Add GPG keys from URL"
    apt_key: url={{item}} state=present
    with_items:
      - https://www.virtualbox.org/download/oracle_vbox.asc
      - https://www.virtualbox.org/download/oracle_vbox_2016.asc
      - https://download.docker.com/linux/ubuntu/gpg

  - name: "Add repositories from URL"
    apt_repository: repo={{item}} state=present
    with_items:
      - deb http://repository.spotify.com testing non-free
      - deb http://download.virtualbox.org/virtualbox/debian {{ansible_lsb.codename}} contrib
      - deb https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable

  - name: "Add repositories from PPA"
    apt_repository: repo={{item}}
    with_items:
      - 'ppa:peterlevi/ppa'
      - 'ppa:team-xbmc/ppa'
  become: true
