---
- name: Install required packages
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present
  with_items:
    - xfonts-terminus
    - vim
    - htop
    - network-manager-openconnect
    - libpython-dev
    - mc
    - vlc
    - kodi
    - calibre
    - fbreader
  become: true

- name: Install required packages from additional repos
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present
  with_items:
    - spotify-client
    - virtualbox-5.1
    - variety
    - variety-slideshow
    - docker-engine
    - docker-compose
  become: true

- include: virtualbox-oracle.yml
