---
- name: Install required packages
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present
  with_items:
    - xfonts-terminus
    - vim
  become: true

- name: Install required packages from additional repos
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present
  with_items:
    - spotify-client
    - virtualbox-5.1
  become: true

- include: virtualbox-oracle.yml
