---
- name: Install required packages
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present
  with_items:
    - xfonts-terminus
    - vim
    - curl
    - htop
    - network-manager-openconnect
    - network-manager-openconnect-gnome
    - wireguard
    - libpython3-dev
    - mc
    - vlc
    - kodi
    - calibre
    - fbreader
    - guake
  become: true

- name: Install required packages from additional repos
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present
  with_items:
    - spotify-client
    - virtualbox-6.1
    - variety
    #- variety-slideshow
    - darktable
    - docker-ce
    - docker-compose
  become: true

- include: virtualbox-oracle.yml
