---
- name: Disable Lid Switch
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^HandleLidSwitch'
    insertafter: '^#HandleLidSwitch'
    line: HandleLidSwitch=ignore
  become: true

- name: Restart systemd-logind
  service:
    name: systemd-logind
    state: restarted
  become: true
